version: '3'
services:
  billservice:
    build:
      context: ./BillService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose: 
      - "8081"
  logisticservice:
    build:
      context: ./LogisticService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    expose:
      - "8082"
  checkout:
    build:
      context: ./Checkout
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose: 
      - "8080"